### ISSUE TITLE
shape '[32, 128, 9, 9]' is invalid for input of size 802816

### ISSUE THREAD

**Issue by youguoda** [wbw520/scouter#10]
Traceback (most recent call last):
  File "D:\PyCharmpro\PyCharm 2021.2.3\plugins\python\helpers\pydev\pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharmpro\PyCharm 2021.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/github code/scouter/train.py", line 238, in <module>
    param_translation(args)
  File "E:/github code/scouter/train.py", line 221, in param_translation
    main(args)
  File "E:/github code/scouter/train.py", line 178, in main
    train_one_epoch(model, data_loader_train, optimizer, device, record, epoch)
  File "E:\github code\scouter\engine.py", line 8, in train_one_epoch
    calculation(model, "train", data_loader, device, record, epoch, optimizer)
  File "E:\github code\scouter\engine.py", line 30, in calculation
    logits, loss_list = model(inputs, labels)
  File "D:\Ruanjian\Anaconda\envs\youda\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
 File "E:\github code\scouter\sloter\slot_model.py", line 108, in forward
    x = self.conv1x1(x.view(x.size(0), self.channel, self.feature_size, self.feature_size))
RuntimeError: shape '[32, 128, 9, 9]' is invalid for input of size 802816

What is the cause of this error?  Can you help me? Thank you very much！

**Comment by Millielele** [comment]
I also meet this problem. could you tell me how to solve it?
